### PR TITLE
eslint rules addition

### PR DESCRIPTION
**Pull request by mubaidr**

### CODE REVIEW

**Comment by mubaidr** [comment]
eslint lint rules updated
eslint dependencies added to package.json
Sort all attribs by order

- eslint lint rules updated
- eslint dependencies added to package.json
- Sort main asset imports

**Comment by mubaidr** [comment]
Ok Now i think this is ready for review. @cristijora Mostly changes are related to eslint configuration (few changes related to notifications tweaks.)

**Comment by cristijora** [comment]
Thanks for the upadte @mubaidr I will take a look at it today and hopefully merge this.

**Comment by cristijora** [comment]
I merged this but added some tweaks/adjustments.
I want to make eslint optional. Although it's very good for open-source stuff it can get annoying while developing prototypes or just wanting to get stuff done quickly.

eslint can be easily enabled/disabled with:
```js 
"dev": "cross-env ENABLE_ESLINT=true node build/dev-server.js" //enabled
"dev": "cross-env ENABLE_ESLINT=false node build/dev-server.js" //disabled
```

**Pull request merged**
